apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: python-test2
  janus-idp.io/tekton: python-test2
  backstage.io/kubernetes-id: python-test2
  backstage.io/kubernetes-namespace: rhtap-test-organization-jk 
  app.kubernetes.io/part-of: python-test2
resources: 
- deployment.yaml
- route.yaml
- service.yaml
