apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: python-test2
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe:3836bbe55e1bf9a7d9239a3ee16b1294fe066121@sha256:482adc2e8f39b021f4f06e36d349f1815bd913eaa2d08e1bb874aea7b5f23cd5
          name: container-image
